name: Release

on:
    workflow_dispatch:
    push:
        branches:
            - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get previous build number
      id: getPreviousBuild
      env:
        BRANCH: ${{ github.ref_name }}
      run: | 
        PREVIOUS_TAG=$(git for-each-ref --sort=-version:refname --count 1 --format="%(refname:short)" "refs/tags/${BRANCH}*")
        if [[ -z "$PREVIOUS_TAG" ]]; then
        # Default build number to 1 if there was no previous tag.
        echo "BUILD_NUMBER=1" >> $GITHUB_ENV
        else
        echo tag=${PREVIOUS_TAG} >> $GITHUB_ENV
        fi
    - name: Get current build number
      id: getCurrentBuild
      env:
        PREVIOUS_TAG: ${{ steps.getPreviousBuild.outputs.tag }}
        BRANCH: ${{ github.ref_name }}
      run: |
        if [[ -z "$PREVIOUS_TAG" ]]; then
        # If PREVIOUS_TAG is empty, we have already set the build number to 1 in the previous step.
        echo "Current build number is 1"
        else
        # Extracting the build number from the tag and incrementing by 1.
        PREVIOUS_BUILD_NUMBER=$(echo $PREVIOUS_TAG | sed "s/${BRANCH}-build-//")
        CURRENT_BUILD_NUMBER=$((PREVIOUS_BUILD_NUMBER + 1))
        echo "Current build number is $CURRENT_BUILD_NUMBER"
        echo "BUILD_NUMBER=$CURRENT_BUILD_NUMBER" >> $GITHUB_ENV
        fi
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        custom_tag: ${{ steps.getCurrentBuild.outputs.tag }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        gradle-home-cache-cleanup: true
    - run: mkdir staging && cp build/libs/CCAbstractMenuLoader.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: CCAbstractMenuLoader-Latest
        path: staging/CCAbstractMenuLoader.jar
    - name: Generate release diff
      env:
        BEGIN_COMMIT: ${{ steps.getPreviousBuild.outputs.tag }}
        END_COMMIT: ${{ steps.getCurrentBuild.outputs.tag }}
      run: git fetch --tags --force && git log --pretty=format:"* %s (%h)" ${BEGIN_COMMIT}..${END_COMMIT} > release_notes.md
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: staging/CCAbstractMenuLoader.jar
        allowUpdates: true
        bodyFile: "release_notes.md"
        draft: false
        prerelease: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
        name: Build ${{ steps.getCurrentBuild.outputs.number }} (${{ github.ref_name }})
        tag: ${{ steps.getCurrentBuild.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}